import { NextResponse } from 'next/server';
import React from 'react';
import { renderToStream } from '@react-pdf/renderer';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

const styles = StyleSheet.create({
    page: { flexDirection: 'column', backgroundColor: '#ffffff', padding: 40 },
    section: { margin: 10, padding: 10, flexGrow: 1 },
    header: { fontSize: 24, marginBottom: 20, textAlign: 'center', color: '#1A365D' },
    score: { fontSize: 48, fontWeight: 'bold', color: '#1A365D', textAlign: 'center', marginBottom: 10 },
    tier: { fontSize: 18, textAlign: 'center', color: '#38B2AC', marginBottom: 30 },
    heading: { fontSize: 16, fontWeight: 'bold', marginBottom: 10, marginTop: 20, color: '#1A365D' },
    text: { fontSize: 12, marginBottom: 5, color: '#4A5568' },
});

const ScorecardPDF = ({ data }: { data: any }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <Text style={styles.header}>Finance Ops Scorecard</Text>

            <View>
                <Text style={styles.score}>{data?.scoreResult?.score || 0}</Text>
                <Text style={styles.tier}>{data?.scoreResult?.tier || 'N/A'}</Text>
            </View>

            <View style={styles.section}>
                <Text style={styles.heading}>Your Top Quick Wins</Text>
                {data?.scoreResult?.quickWins?.map((win: string, i: number) => (
                    <Text key={i} style={styles.text}>• {win}</Text>
                ))}
            </View>

            <View style={styles.section}>
                <Text style={styles.heading}>30/60/90 Day Plan</Text>
                <Text style={styles.text}>1. (Day 30) Implement Cloud Accounting System.</Text>
                <Text style={styles.text}>2. (Day 60) Define Month-End Close Checklist.</Text>
                <Text style={styles.text}>3. (Day 90) Automate AP/AR with Dext/Stripe.</Text>
            </View>

            <Text style={[styles.text, { fontSize: 10, marginTop: 40, textAlign: 'center', color: '#CBD5E0' }]}>
                Generated by Ledger Logic • Not Legal Advice
            </Text>
        </Page>
    </Document>
);

export async function GET(req: Request) {
    const { searchParams } = new URL(req.url);
    const mockData = {
        scoreResult: {
            score: 75,
            tier: 'Scale-Ready',
            quickWins: ['Fix Xero bank feeds', 'Automate Dext', 'Review cash flow']
        }
    };
    const stream = await renderToStream(<ScorecardPDF data={mockData} />);
    return new NextResponse(stream as any, {
        headers: {
            'Content-Type': 'application/pdf',
            'Content-Disposition': 'attachment; filename="FinanceOps_Report.pdf"'
        }
    });
}
